build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
        tests:
            environment:
                php:
                    version: 7.1
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=clover'
                        coverage:
                            file: 'clover'
                            format: 'clover'
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        code_rating: true
        duplication: true

