<?php
/**
 * Created by PhpStorm.
 * User: k4io_
 * Date: 04/10/2018
 * Time: 15:25
 */

require_once 'Conexao.php';

class Pessoas extends Conexao
{
    private $id;
    private $nome;
    private $email;

    public function conecta()
    {
        return parent::conecta(); // TODO: Change the autogenerated stub
    }


    public function seleciona($id)
    {
        try {
            $con = $this->conecta();
            $resul = $con->prepare("select * from pessoa where id = ?");
            $resul->bindValue(1, $id);
            $resul->execute();
            $con = null;
            if ($resul->rowCount() > 0) {
                $resul = $resul->fetch();
                $this->id = $resul[0];
                $this->nome = $resul[1];
                $this->email = $resul[2];
            } else {
                return 0;
            }
        } catch (PDOException $e) {
            return $e->getMessage();
        }
    }
    public function listaPessoas()
    {
        try {
            $con = $this->conecta();
            $resul = $con->prepare("select * from pessoa");
            $resul->execute();
            $con = null;
            return $resul->fetchAll();
        } catch (PDOException $e) {
            return $e->getMessage();
        }
    }

    public function salvar()
    {
        try {
            $con = $this->conecta();
            $sql = $con->prepare('insert into pessoa(nome,email) values (?,?)');
            $sql->bindValue(1, $this->nome);
            $sql->bindValue(2, $this->email);
            $sql->execute();
            $this->id = $con->lastInsertId();
            return true;
        } catch (PDOException $e) {
            return $e->getMessage();
        }
    }

    public function atualizar()
    {
        try {
            $con = $this->conecta();
            $resul = $con->prepare("update pessoa set nome = ?, email = ? where id = ?");
            $resul->bindValue(1, $this->nome);
            $resul->bindValue(2, $this->email);
            $resul->bindValue(3, $this->id);
            $resul->execute();
            $con = null;
            return true;
        } catch
        (PDOException $e) {
            return $e->getMessage();
        }
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getNome()
    {
        return $this->nome;
    }

    /**
     * @param mixed $nome
     */
    public function setNome($nome): void
    {
        $this->nome = $nome;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email): void
    {
        $this->email = $email;
    }


}

$p1 = new Pessoas();
//$p1->setNome('vinicius');
//$p1->setEmail('vinicius@kaio');
//$p1->salvar();

$p1->seleciona(2);
echo $p1->getNome();
$p1->setNome('luiz');
$p1->atualizar();
echo $p1->getNome();


echo "<br>";
$p2 = new Pessoas();
//print_r($p2->listaPessoas());
/*foreach($p2->listaPessoas() as $pes){
    echo 'nome: '.$pes['nome'].'<br>';
}*/